package bo.edu.ucbcba.videoclub.view;

import bo.edu.ucbcba.videoclub.controller.ClientController;
import bo.edu.ucbcba.videoclub.controller.Session;
import bo.edu.ucbcba.videoclub.exceptions.ValidationException;
import bo.edu.ucbcba.videoclub.model.Client;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 * Created by privado on 16/05/2016.
 */
public class ClientsForm extends JFrame {
    private JButton viewClientsButton;
    private JButton addClientsButton;
    private JPanel rootPanel;
    private JButton homeButton;
    private JButton deleteClientButton;

    public ClientsForm(JFrame parent) {
        super("Clients");
        setContentPane(rootPanel);
        setSize(600, 400);
        //setBounds(200, 300, 600, 400);
        pack();
        setResizable(true);
        launchImage();
        addClientsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                launchClientRegister();
            }
        });

        viewClientsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                viewClients();
            }
        });

        if (Session.getSession().getUtype() == 1) {
            deleteClientButton.setVisible(true);
        } else {
            deleteClientButton.setVisible(false);
        }

        deleteClientButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                viewDeleteClient();
            }
        });

        homeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showHome();
            }
        });
    }

    private void showHome() {
        this.setVisible(false);
        InitialForm form = new InitialForm();
        form.setVisible(true);
        form.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    private void launchClientRegister() {
        ClientRegister form = new ClientRegister(this);
        form.setVisible(true);
    }

    private void viewClients() {
        ViewClientsForm form = new ViewClientsForm(this);
        form.setVisible(true);
    }

    public void viewDeleteClient() {
        DeleteClientForm form = new DeleteClientForm(this);
        form.setVisible(true);
    }

    private void launchImage() {
        BufferedImage myPicture = null;
        try {
            myPicture = ImageIO.read(new File("fondo.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        JLabel label = new JLabel(new ImageIcon(myPicture));
        ((JPanel) getContentPane()).setOpaque(false);
        getLayeredPane().add(label, JLayeredPane.FRAME_CONTENT_LAYER);
        label.setBounds(0, 0, myPicture.getWidth(), myPicture.getHeight());

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setBackground(new Color(-3090213));
        rootPanel.setForeground(new Color(-3090213));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("Courier New", Font.BOLD, 26));
        label1.setForeground(new Color(-4486332));
        label1.setText("Clients");
        rootPanel.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewClientsButton = new JButton();
        viewClientsButton.setBackground(new Color(-12828863));
        viewClientsButton.setFont(new Font("Courier New", viewClientsButton.getFont().getStyle(), 18));
        viewClientsButton.setForeground(new Color(-4486332));
        viewClientsButton.setText("View Clients");
        rootPanel.add(viewClientsButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(1, 2, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(100, 200), null, new Dimension(100, 200), 0, false));
        final Spacer spacer2 = new Spacer();
        rootPanel.add(spacer2, new GridConstraints(1, 0, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(100, 200), null, new Dimension(100, 200), 0, false));
        addClientsButton = new JButton();
        addClientsButton.setBackground(new Color(-12828863));
        addClientsButton.setFont(new Font("Courier New", addClientsButton.getFont().getStyle(), 18));
        addClientsButton.setForeground(new Color(-4486332));
        addClientsButton.setText("Add Client");
        rootPanel.add(addClientsButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        homeButton = new JButton();
        homeButton.setBackground(new Color(-12828863));
        homeButton.setFont(new Font("Courier New", Font.BOLD, 20));
        homeButton.setForeground(new Color(-6836293));
        homeButton.setText("Home");
        rootPanel.add(homeButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteClientButton = new JButton();
        deleteClientButton.setBackground(new Color(-12828863));
        deleteClientButton.setFont(new Font("Courier New", deleteClientButton.getFont().getStyle(), 18));
        deleteClientButton.setForeground(new Color(-4486332));
        deleteClientButton.setText("Delete Client");
        rootPanel.add(deleteClientButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
