package bo.edu.ucbcba.videoclub.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by USER on 17/05/2016.
 */
public class HomeMoviesForm extends JFrame {
    private JPanel rootPanel;
    private JButton viewButton;
    private JButton addButton;
    private JButton homeButton;

    public HomeMoviesForm(InitialForm parent) {
        super("Home Movies");
        setContentPane(rootPanel);
        setSize(400, 400);
        setResizable(true);
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                launchRegister();
            }
        });

        viewButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                launchview();
            }
        });
    }

    private void launchview() {
        ViewMoviesForm form = new ViewMoviesForm(this);
        form.setVisible(true);
    }

    private void launchRegister() {
        RegisterMovieForm form = new RegisterMovieForm(this);
        form.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setBackground(new Color(-3090213));
        rootPanel.setForeground(new Color(-3090213));
        viewButton = new JButton();
        viewButton.setBackground(new Color(-12828863));
        viewButton.setFont(new Font("Courier New", viewButton.getFont().getStyle(), 18));
        viewButton.setForeground(new Color(-4486332));
        viewButton.setText("View");
        rootPanel.add(viewButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        homeButton = new JButton();
        homeButton.setBackground(new Color(-12828863));
        homeButton.setFont(new Font("Courier New", homeButton.getFont().getStyle(), 18));
        homeButton.setForeground(new Color(-6836293));
        homeButton.setText("Home");
        rootPanel.add(homeButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addButton = new JButton();
        addButton.setBackground(new Color(-12828863));
        addButton.setFont(new Font("Courier New", addButton.getFont().getStyle(), 18));
        addButton.setForeground(new Color(-4486332));
        addButton.setText("Add");
        rootPanel.add(addButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("Courier New", Font.BOLD, 20));
        label1.setForeground(new Color(-4486332));
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("MOVIES");
        rootPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
