package bo.edu.ucbcba.videoclub.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class InitialForm extends JFrame {
    private JPanel rootPanel;
    private JButton MoviesButton;
    private JButton CustomersButton;
    private JButton GamesButton;

    public InitialForm() {
        super("Welcome");
        setContentPane(rootPanel);
        setSize(600, 400);
        MoviesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MoviesZone();
            }
        });

        CustomersButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                launchClientsForm();
            }
        });

        GamesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                launchGames();
            }
        });

    }

    private void launchGames() {
        GamesForm form = new GamesForm(this);
        form.setVisible(true);
    }

    private void launchClientsForm() {
        ClientsForm form = new ClientsForm(this);
        form.setVisible(true);
    }

    private void MoviesZone() {
        MoviesForm form = new MoviesForm(this);
        form.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 5, new Insets(2, 2, 2, 2), -1, -1));
        rootPanel.setEnabled(false);
        rootPanel.setFont(new Font(rootPanel.getFont().getName(), rootPanel.getFont().getStyle(), rootPanel.getFont().getSize()));
        rootPanel.putClientProperty("html.disable", Boolean.FALSE);
        final JLabel label1 = new JLabel();
        label1.setEnabled(false);
        label1.setFont(new Font("Constantia", label1.getFont().getStyle(), 28));
        label1.setText("SAKILA 2.0");
        rootPanel.add(label1, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        GamesButton = new JButton();
        GamesButton.setFont(new Font("Aharoni", GamesButton.getFont().getStyle(), 20));
        GamesButton.setHideActionText(false);
        GamesButton.setText("Juegos");
        rootPanel.add(GamesButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MoviesButton = new JButton();
        MoviesButton.setFont(new Font("Aharoni", MoviesButton.getFont().getStyle(), 20));
        MoviesButton.setHorizontalTextPosition(11);
        MoviesButton.setText("Peliculas");
        rootPanel.add(MoviesButton, new GridConstraints(1, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CustomersButton = new JButton();
        CustomersButton.setEnabled(true);
        CustomersButton.setFont(new Font("Aharoni", CustomersButton.getFont().getStyle(), 20));
        CustomersButton.setHideActionText(false);
        CustomersButton.setText("Clientes");
        rootPanel.add(CustomersButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
