package bo.edu.ucbcba.videoclub.view;

import bo.edu.ucbcba.videoclub.controller.CompanyController;
import bo.edu.ucbcba.videoclub.exceptions.ValidationException;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 * Created by Samuel on 29/05/2016.
 */
public class RegisterCompanyForm extends JDialog {
    private JPanel rootPanel;
    private JTextField nameTextField;
    private JButton saveButton;
    private JButton cancelButton;
    private JComboBox CountrycomboBox;
    private CompanyController controller;

    public RegisterCompanyForm(HomeGamesForm parent) {
        super(parent, "Register Company");
        setContentPane(rootPanel);
        setSize(300, 300);
        setResizable(false);
        launchImage();
        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveCompany();
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cancel();
            }
        });

        controller = new CompanyController();

    }

    private void cancel() {
        setVisible(false);
        dispose();
    }

    private void saveCompany() {
        try {
            String name = nameTextField.getText();
            String country = (String) CountrycomboBox.getSelectedItem();
            controller.create(name, country);
            JOptionPane.showMessageDialog(this, "Company created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            cancel();
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Format error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void launchImage() {
        BufferedImage myPicture = null;
        try {
            myPicture = ImageIO.read(new File("fondo.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        JLabel label = new JLabel(new ImageIcon(myPicture));
        ((JPanel) getContentPane()).setOpaque(false);
        getLayeredPane().add(label, JLayeredPane.FRAME_CONTENT_LAYER);
        label.setBounds(0, 0, myPicture.getWidth(), myPicture.getHeight());

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(6, 9, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, label1.getFont().getSize()));
        label1.setText("RegisterCompanty");
        rootPanel.add(label1, new GridConstraints(0, 1, 1, 7, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        rootPanel.add(nameTextField, new GridConstraints(1, 2, 1, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(0, 8, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        rootPanel.add(spacer2, new GridConstraints(1, 8, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        rootPanel.add(spacer3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, label2.getFont().getSize()));
        label2.setText("Name");
        rootPanel.add(label2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        rootPanel.add(spacer4, new GridConstraints(4, 8, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setBackground(new Color(-12828863));
        saveButton.setForeground(new Color(-4420796));
        saveButton.setIcon(new ImageIcon(getClass().getResource("/icons/add.png")));
        saveButton.setText("Save");
        rootPanel.add(saveButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelButton = new JButton();
        cancelButton.setBackground(new Color(-12828863));
        cancelButton.setForeground(new Color(-4420796));
        cancelButton.setIcon(new ImageIcon(getClass().getResource("/icons/remove-symbol.png")));
        cancelButton.setText("Cancel");
        rootPanel.add(cancelButton, new GridConstraints(4, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CountrycomboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Australia");
        defaultComboBoxModel1.addElement("Austria");
        defaultComboBoxModel1.addElement("Beralus");
        defaultComboBoxModel1.addElement("Belgium");
        defaultComboBoxModel1.addElement("Brazil");
        defaultComboBoxModel1.addElement("Bulgaria");
        defaultComboBoxModel1.addElement("Canada");
        defaultComboBoxModel1.addElement("Chile");
        defaultComboBoxModel1.addElement("China");
        defaultComboBoxModel1.addElement("Croatia");
        defaultComboBoxModel1.addElement("Czech Republic");
        defaultComboBoxModel1.addElement("Denmark");
        defaultComboBoxModel1.addElement("Estonia");
        defaultComboBoxModel1.addElement("Finland");
        defaultComboBoxModel1.addElement("France");
        defaultComboBoxModel1.addElement("Germany");
        defaultComboBoxModel1.addElement("Greece");
        defaultComboBoxModel1.addElement("Hungary");
        defaultComboBoxModel1.addElement("India");
        defaultComboBoxModel1.addElement("Ireland");
        defaultComboBoxModel1.addElement("Italy");
        defaultComboBoxModel1.addElement("Japan");
        defaultComboBoxModel1.addElement("Netherlands");
        defaultComboBoxModel1.addElement("New Zealand");
        defaultComboBoxModel1.addElement("Norway");
        defaultComboBoxModel1.addElement("Pakistan");
        defaultComboBoxModel1.addElement("Philippines");
        defaultComboBoxModel1.addElement("Poland");
        defaultComboBoxModel1.addElement("Romania");
        defaultComboBoxModel1.addElement("Russia");
        defaultComboBoxModel1.addElement("Serbia");
        defaultComboBoxModel1.addElement("Slovakia");
        defaultComboBoxModel1.addElement("Slovenia");
        defaultComboBoxModel1.addElement("South Korea");
        defaultComboBoxModel1.addElement("Spain");
        defaultComboBoxModel1.addElement("Sweden");
        defaultComboBoxModel1.addElement("Taiwan");
        defaultComboBoxModel1.addElement("Thailand");
        defaultComboBoxModel1.addElement("Turkey");
        defaultComboBoxModel1.addElement("Ukraine");
        defaultComboBoxModel1.addElement("United Kingdom");
        defaultComboBoxModel1.addElement("United States");
        CountrycomboBox.setModel(defaultComboBoxModel1);
        rootPanel.add(CountrycomboBox, new GridConstraints(3, 2, 1, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, label3.getFont().getSize()));
        label3.setText("Country");
        rootPanel.add(label3, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setOpaque(true);
        rootPanel.add(panel1, new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
